back/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

import account

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('account.urls')),
  path('oauth/', account.views.oauth, name='oauth'),
  path('', TemplateView.as_view(template_name='base.html'), name='base'),
  path('product/', include('product.urls')),
  path('comment/', include('comment.urls')),

  # api
  path('api/products/', include('product.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/product/api/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter
from product.api.views import product_create_or_list, product_detail

# from product.api.views import ProductViewSet

# TODO: SimpleRouter vs DefaultRouter 차이점
# router = SimpleRouter()
# router.register('', ProductViewSet)


urlpatterns = [
    # POST /api/products/cart/change_quantity/
    # path('cart/change_quantity/', change_quantity_api_view),

    # DELETE /api/products/cart/:cart_item_id/
    # path('cart/:cart_item_id/', cart_delete_view, name='cart_delete'),

    # path('', include(router.urls)),

    # REST 개념

    # Rest 에서는 리소스 정의,
    # 생성 POST /{리소스}
    #

    # 상품 추가 : POST /api/products/
    # 상품 목록 조회 : GET /api/products/
    path('', product_create_or_list),

    # 상품 상세 조회 : GET /api/products/<int:pk>/
    # 상품 수정 : PUT /api/products/products/<int:pk>/
    # 상품 삭제 : DELETE /api/products/products/<int:pk>/
    path('<int:pk>/', product_detail),


]

back/product/urls.py
from django.urls import path, include
from product.views import (
    ProductCreateView,
    ProductDetailView,
    ProductDeleteView,
    product_list_view,
    add_cart_view,
    cart_items_view,
    cart_change_view,
    cart_delete_view,
)

from rest_framework.routers import DefaultRouter



app_name = 'product'

urlpatterns = [
    path('list/', product_list_view, name='list'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProductDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('add_cart/', add_cart_view, name='add_cart'),
    path('cart_items/', cart_items_view, name='cart_items'),
    path('cart_change/', cart_change_view, name='cart_change'),
    path('cart_delete/', cart_delete_view, name='cart_delete'),
]

back/product/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='상품명')
    seller = models.CharField(max_length=200, null=True, verbose_name='입점사')
    price = models.PositiveIntegerField(verbose_name='가격(원)')
    image = models.ImageField(upload_to='product/', verbose_name='사진')
    description = models.TextField(verbose_name='상품설명')

    def __str__(self):
        return f'{self.seller}::{self.name}'


class ProductOption(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.CharField(max_length=100, verbose_name='사이즈')
    color = models.CharField(max_length=100, verbose_name='색상')
    stock_count = models.PositiveIntegerField(verbose_name='재고')

    def __str__(self):
        return f'{self.product_id}::{self.size}::{self.color}'


class CartItem(models.Model):
    user = models.ForeignKey('local_account.User', on_delete=models.CASCADE, verbose_name='구매유저')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='구매상품')
    product_option = models.ForeignKey(ProductOption,
                                       on_delete=models.PROTECT, verbose_name='구매상품의 옵션')
    quantity = models.IntegerField(verbose_name='구매수량')

    def __str__(self):
        return f'{self.user_id}::{self.product_id}::{self.product_option_id}::{self.quantity}'


class Order(models.Model):
    user = models.ForeignKey('local_account.User', on_delete=models.CASCADE, verbose_name='구매유저')
    ordered_date = models.DateTimeField()

    def __str__(self):
        return f'{self.user_id}::{self.ordered_date}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='구매상품')
    product_option = models.ForeignKey(ProductOption,
                                       on_delete=models.PROTECT, verbose_name='구매상품의 옵션')
    quantity = models.IntegerField(verbose_name='구매수량')

    def __str__(self):
        return f'{self.order_id}::{self.product_id}::{self.product_option_id}::{self.quantity}'

back/product/forms.py
from django import forms
from django.forms import ModelForm
from product.models import Product, ProductOption


class ProductCreationForm(ModelForm):
    class Meta:
        model = Product
        fields = [
            'name',
            'price',
            'description',
            'image',
            'seller',
        ]


class ProductPurchaseForm(forms.Form):
    def __init__(self, product, *args, **kwargs):
        super().__init__(*args, **kwargs)

        options = ProductOption.objects.filter(product=product).order_by('size', 'color')
        choices = []
        for option in options:
            choices.append((option.id, f'{option.size}/{option.color}'))
        if not choices:
            choices = [(0, '재고없음')]

        self.fields['product_option'] = forms.ChoiceField(choices=choices)
        self.fields['product_option'].label = ''

back/product/api/views.py
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.decorators import api_view

from rest_framework.response import Response


from product.api.serializers import ProductSerializer
from product.models import Product


def create_product(request):
    serializer = ProductSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=201)
    return Response(serializer.errors, status=400)


def list_product():
    serializer = ProductSerializer(Product.objects.all(), many=True)
    return Response(serializer.data)


def retrieve_product(product):
    serializer = ProductSerializer(product)
    return Response(serializer.data)


def update_product(product, request):
    serializer = ProductSerializer(product, data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def delete_product(product):
    product.delete()
    return Response(status=status.HTTP_204_NO_CONTENT)


@api_view(['GET', 'POST'])
def product_create_or_list(request):
    if request.method == 'GET':
        return list_product()
    else:
        return create_product(request)


@api_view(['GET', 'PUT', 'DELETE'])
def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'GET':
        return retrieve_product(product)
    elif request.method == 'PUT':
        return update_product(product, request)
    else:
        return delete_product(product)

back/product/views.py
import json
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, DeleteView
from django.views.generic.edit import FormMixin
from comment.forms import CommentCreationForm
from product.forms import ProductCreationForm, ProductPurchaseForm
from product.models import ProductOption, CartItem

from rest_framework.viewsets import ModelViewSet
from product.api.serializers import ProductSerializer
from .models import Product


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductCreationForm
    template_name = 'product/create.html'

    def get_success_url(self):
        return reverse('product:detail', kwargs={'pk': self.object.pk})


class ProductDetailView(DetailView, FormMixin):
    model = Product
    form_class = CommentCreationForm
    context_object_name = 'target_product'
    template_name = 'product/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['purchases_form'] = ProductPurchaseForm(self.object)
        return context


class ProductDeleteView(DeleteView):
    model = Product
    context_object_name = 'target_product'
    success_url = reverse_lazy('product:list')
    template_name = 'product/delete.html'


PRODUCT_PAGE_SIZE = 5


def product_list_view(request):
    # 1. 파라미터를 받는다. name, page
    search_value = request.GET.get('search')

    search_filter = Q()
    if search_value:
        search_filter |= Q(name__contains=search_value)
        search_filter |= Q(description__contains=search_value)

    products = Product.objects.filter(search_filter)

    page = request.GET.get('page')

    # 3. 결과 쿼리셋에 대한 페이지네이터 객체를 만든다
    paginator = Paginator(products, PRODUCT_PAGE_SIZE)

    # 4. 페이지네이터를 통해 페이징 처리 된 페이지 객체를 구한다
    page_obj = paginator.get_page(page)

    # 5. 템플릿을 통해 렌더링 한다. 필요한 파라미터들은 context 에 싣어서 함께 전달한다
    return render(
        request,
        'product/list.html',
        context={
            'paginator': paginator,
            'page_obj': page_obj,
            'product_list': page_obj.object_list,
        }
    )


@login_required()
def add_cart_view(request):
    product_option_id = request.POST.get('product_option')
    product_option_id = int(product_option_id)
    product_option = ProductOption.objects.get(id=product_option_id)

    try:
        cart_item = CartItem.objects.get(user=request.user, product_option=product_option)
        cart_item.quantity += 1
        cart_item.save()

    except CartItem.DoesNotExist:
        CartItem.objects.create(
            user=request.user,
            product_option=product_option,
            product=product_option.product,
            quantity=1
        )
    return redirect('product:cart_items')


@login_required
def cart_items_view(request):
    cart_items = CartItem.objects.filter(user=request.user).order_by('id')
    return render(request, 'product/cart_items.html', context={'cart_items': cart_items})


def cart_change_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        print(data)
        print(data.get('id'))

        cart_item = CartItem.objects.get(user=request.user, id=data.get('id'))
        cart_item.quantity = data.get('quantity')
        cart_item.save()

    return JsonResponse(data)


def cart_delete_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        print(data)

        cart_item = CartItem.objects.get(user=request.user, id=data.get('id'))
        cart_item.delete()

    return JsonResponse(data)

back/templates/product/cart_items.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<table class="table table-image">
    <thead>
    <tr>
        <th scope="col">번호</th>
        <th scope="col">사진</th>
        <th scope="col">상품명</th>
        <th scope="col">색상</th>
        <th scope="col">사이즈</th>
        <th scope="col">수량</th>
    </tr>
    </thead>
    <tbody>
    {% for cart in cart_items %}
    <tr id="table_row{{cart.id}}">
        <th id="id{{cart.id}}">{{ cart.id }}</th>
        <th id="{{cart.id}}"><img class="img-fluid " style=" width:40px; border-radius: 1rem; "
                                  src="{{ cart.product.image.url }}" alt=""></th>
        <td id="name{{cart.id}}"><p>{{ cart.product.name }}</td>
        <td id="color{{cart.id}}">{{ cart.product_option.color }}</td>
        <td id="size{{cart.id}}">{{ cart.product_option.size }}</td>
        <td id="numberUpDown{{cart.id}}">{{ cart.quantity }}</td>
        <td><input type="button" class="btn btn-success" id="increaseQuantity{{cart.id}}" value="▲">
            <input type="button" class="btn btn-warning" id="decreaseQuantity{{cart.id}}" value="▼">
            <input type="button" class="btn btn-danger" id="change{{cart.id}}" value="적용"></td>
        <td><input type="button" class="btn btn-dark" id="delete{{cart.id}}" value="삭제"></td>
        <td></td>
    </tr>
    {% endfor%}
    </tbody>
</table>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>

//수량변경
{% for cart in cart_items %}
        $('#decreaseQuantity'+{{cart.id}}).click(function(e){

                var stat = $('#numberUpDown'+{{cart.id}}).text();
                var num = parseInt(stat,10);
                num--;

            if(num<=0){
                alert('더이상 줄일수 없습니다.');
                num =1;
            }
        $('#numberUpDown'+{{cart.id}}).text(num);
        });
        $('#increaseQuantity'+{{cart.id}}).click(function(e){
            e.preventDefault();
                var stat = $('#numberUpDown'+{{cart.id}}).text();
                var num = parseInt(stat,10);
                num++;

            if(num>100){
                alert('더이상 늘릴수 없습니다.');
                num=100;
            }
        $('#numberUpDown'+{{cart.id}}).text(num);
        });
 {% endfor%}

 // 변경저장
    let change =null;
{% for cart in cart_items %}
     change = document.querySelector('#change'+{{cart.id}});

    change.addEventListener('click', e=> {
        let id = $('#id'+{{cart.id}}).text();
        let name = $('#name'+{{cart.id}}).text();
        let color = $('#color'+{{cart.id}}).text();
        let size = $('#size'+{{cart.id}}).text();
        let quantity = $('#numberUpDown'+{{cart.id}}).text();

        let param = {
            'id': id,
            'name' : name,
            'color' : color,
            'size' : size,
            'quantity' : quantity,

                }

            $.ajax({
                url : '{% url 'product:cart_change' %}',
                type : 'POST',
                headers: {
                  'X-CSRFTOKEN' : '{{ csrf_token }}'
                },
                data : JSON.stringify(param),
                success:function(data){
                    alert('변경 완료');
                    console.log("data pass success",data);
                },
                error: function(){
                    alert('변경 실패');
                }
            });
        });
{% endfor%}


//삭제
{% for cart in cart_items %}
     $('#delete'+{{cart.id}}).click(function(e){

        let id = $('#id'+{{cart.id}}).text();
        let name = $('#name'+{{cart.id}}).text();
        let color = $('#color'+{{cart.id}}).text();
        let size = $('#size'+{{cart.id}}).text();
        let quantity = $('#numberUpDown'+{{cart.id}}).text();

        let param = {
            'id': id,
            'name' : name,
            'color' : color,
            'size' : size,
            'quantity' : quantity,

                }

        var row = $('#table_row'+{{cart.id}});
        row.remove();

        $.ajax({
                url : '{% url 'product:cart_delete' %}',
                type : 'POST',
                headers: {
                  'X-CSRFTOKEN' : '{{ csrf_token }}'
                },
                data : JSON.stringify(param),
                success:function(data){
                    alert('삭제 완료');
                    console.log("data pass success",data);
                },
                error: function(){
                    alert('삭제 실패');
                }
            });

     });
{% endfor%}
</script>

{% endblock %}

back/templates/product/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Product Create</h4>
    </div>
    <form action="{% url 'product:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>


{% endblock %}

back/templates/product/delete.html
{% extends 'base.html' %}


{% block content %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>삭제 : {{ target_product.name }}</h4>
    </div>
    <form action="{% url 'product:delete' pk=target_product.pk %}" method="post">
        {% csrf_token %}

        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>


{% endblock %}

back/templates/product/detail.html
{% extends 'base.html' %}

{% load bootstrap5 %}


{% block content %}
    <div style="text-align: center; max-width: 1000px; margin: 4rem auto;">

        <h1>
            {{ target_product.name }}
        </h1>
        <h5>
            seller : {{ target_product.seller }}
        </h5>
        <hr>

        <img style="width:40%; border-radius: 1rem; margin: 2rem 0 "
                src="{{ target_product.image.url }}" alt="">


            <form action="{% url 'product:add_cart' %}" method="post" style="max-width: 500px; margin: 4rem auto;">
                {% csrf_token %}
                <p>사이즈/색상 선택</p>
                {% bootstrap_form purchases_form %}
                <input type="submit" value="장바구니 담기" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>


        <br>
        <p style="margin: 4rem auto;">
            {{ target_product.description }}
        </p>

        {% if target_product.seller == user %}
        <a href="{% url 'product:delete' pk=target_product.pk %}"
        class="btn btn-danger rounded-pill col-3">
            <p>Delete Product</p>
        </a>
        {% endif %}
        <hr>

        {% for comment in target_product.comment.all %}
            {% include 'comment/detail.html' with comment=comment %}
        {% endfor %}

        {% include 'comment/create.html' with product=target_product %}

    </div>

{% endblock %}

back/templates/product/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<script src="https://cdn.tailwindcss.com"></script>
<section class="section-1">
    <div class="container mx-auto m-5">
        <ul class="prod-list grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-5">
            {% if product_list %}
            {% for product in product_list %}
            <li>
                <a href="{% url 'product:detail' pk=product.pk %}" class="block t-w-full ">
                    <img src="{{ product.image.url }}" alt="" class="block t-w-full">
                    <span class="block text-center mt-1">{{ product.name}}</span>
                    <sapn class="block text-center mt-1">{{ product.price}}</sapn>
                </a>
            </li>
            {% endfor %}
            {% else %}
            <div style="t-text-align:center">
                <h1> No Product </h1>
            </div>
            {% endif %}
        </ul>
    </div>
</section>

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

    {% include 'product/search_form.html' %}


{% endblock %}

back/templates/product/list_original.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    .container {
        padding: 0;
        margin: 0, auto;
    }
    .container a {
      width: 45%;
      max-width: 250px;
    }
    .container div {
      justify-content: center;
      align-items: center;
      border-radius: 1rem;
    }
    .container img {
      width: 100%;
      border-radius: 1rem;
    }

</style>

{% if product_list %}
<div class="container">
    {% for product in product_list %}
    <a href="{% url 'product:detail' pk=product.pk %}">
        {% include 'snippets/card.html' with product=product %}
    </a>
    {% endfor %}
</div>

<script src="{% static 'js/magicgrid.js' %}"></script>

{% else %}
<div style="text-align:center">
    <h1> No Product </h1>
</div>
{% endif %}

{% include 'snippets/pagination.html' with page_obj=page_obj %}

{% include 'product/search_form.html' %}

{% endblock %}

back/templates/product/search_form.html
<div style="text-align:center; ">
    <form method='get' action=''>
        <input type="text" name ='search' placeholder='검색'/>
        <input type="submit" value='검색'/>
    </form>
</div>