back/account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from account.views import (
    AccountCreateView,
    find_username_view,
    reset_password_view,
    change_password_view, oauth, kakao_login_view,
)

app_name = "account"

urlpatterns = [
    path('signup/', AccountCreateView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('kakao_login/', kakao_login_view, name='kakao_login'),
    path('oauth/', oauth, name='oauth'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('find_username/', find_username_view, name='find_username'),
    path('reset_password/', reset_password_view, name='reset_password'),
    path('change_password/', change_password_view, name='change_password'),

]

back/comment/urls.py
from django.urls import path

from comment.views import CommentCreateView, CommentDeleteView

app_name = 'comment'

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),

]

back/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

import account

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('account.urls')),
  path('oauth/', account.views.oauth, name='oauth'),
  path('', TemplateView.as_view(template_name='base.html'), name='base'),
  path('product/', include('product.urls')),
  path('comment/', include('comment.urls')),

  # api
  path('api/products/', include('product.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/comment/models.py
from django.db import models
from account.models import User
from product.models import Product


class Comment(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.SET_NULL,
                                null=True, related_name='comment',
                                verbose_name='상품')
    writer = models.ForeignKey(User,
                               on_delete=models.SET_NULL,
                               null=True,
                               related_name='comment',
                               verbose_name='작성자')
    content = models.TextField(null=False)
    created_at = models.DateField(auto_now=True)

back/comment/forms.py
from django.forms import ModelForm

from comment.models import Comment


class CommentCreationForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

back/comment/views.py
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView

from comment.decorators import comment_owner
from comment.forms import CommentCreationForm
from comment.models import Comment
from product.models import Product


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentCreationForm
    template_name = 'comment/create.html'

    def form_valid(self, form):
        temp_comment = form.save(commit=False)
        temp_comment.product = Product.objects.get(pk=self.request.POST['product_pk'])
        temp_comment.writer = self.request.user
        temp_comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('product:detail', kwargs={'pk': self.object.product.pk})


@method_decorator(comment_owner, 'get')
@method_decorator(comment_owner, 'post')
class CommentDeleteView(DeleteView):
    model = Comment
    context_object_name = 'target_comment'
    template_name = 'comment/delete.html'

    def get_success_url(self):
        return reverse('product:detail', kwargs={'pk': self.object.product.pk})

back/templates/comment/create.html
{% load bootstrap5 %}

{% block content %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>질문 작성하기</h4>
    </div>
    <form action="{% url 'comment:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% if user.is_authenticated %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        {% else %}
        <a href="{% url 'account:login' %}?next={{ request.path }}"
           class="btn btn-dark rounded-pill col-6 mt-3">
            Login
        </a>
        {% endif %}


        <input type="hidden" name="product_pk" value="{{ product.pk }}">
    </form>
</div>


{% endblock %}

back/templates/comment/delete.html
{% extends 'base.html' %}


{% block content %}
<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div class="mb-4">
    <h4>질문 삭제 : {{ target_comment.content }}</h4>
  </div>
  <form action="{% url 'comment:delete' pk=target_comment.pk %}" method="post">
    {% csrf_token %}

    <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
  </form>
</div>


{% endblock %}

back/templates/comment/detail.html
<div style="border: 1px solid; text-align:left; padding: 4%; margin: 1rem 0; border-radius: 1rem;
            border-color: #bbb;">
    <div>
        <strong>
            {{ comment.writer.username }}
        </strong>
        {{ comment.created_at }}
    </div>
    <div style="margin: 1rem 0;">
        {{ comment.content }}
    </div>
    {% if comment.writer == user  %}
    <div style="text-align: right">
        <a href="{% url 'comment:delete' pk=comment.pk %}"
           class="btn btn-danger rounded-pill">
            Delete
        </a>
    </div>
    {% endif %}
</div>