back/account/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from account.views import (
    AccountCreateView,
    find_username_view,
    reset_password_view,
    change_password_view, oauth, kakao_login_view,
)

app_name = "account"

urlpatterns = [
    path('signup/', AccountCreateView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('kakao_login/', kakao_login_view, name='kakao_login'),
    path('oauth/', oauth, name='oauth'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('find_username/', find_username_view, name='find_username'),
    path('reset_password/', reset_password_view, name='reset_password'),
    path('change_password/', change_password_view, name='change_password'),

]

back/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

import account

urlpatterns = [
  path('admin/', admin.site.urls),
  path('accounts/', include('account.urls')),
  path('oauth/', account.views.oauth, name='oauth'),
  path('', TemplateView.as_view(template_name='base.html'), name='base'),
  path('product/', include('product.urls')),
  path('comment/', include('comment.urls')),

  # api
  path('api/products/', include('product.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/product/urls.py
from django.urls import path, include
from product.views import (
    ProductCreateView,
    ProductDetailView,
    ProductDeleteView,
    product_list_view,
    add_cart_view,
    cart_items_view,
    cart_change_view,
    cart_delete_view,
)

from rest_framework.routers import DefaultRouter



app_name = 'product'

urlpatterns = [
    path('list/', product_list_view, name='list'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProductDetailView.as_view(), name='detail'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('add_cart/', add_cart_view, name='add_cart'),
    path('cart_items/', cart_items_view, name='cart_items'),
    path('cart_change/', cart_change_view, name='cart_change'),
    path('cart_delete/', cart_delete_view, name='cart_delete'),
]

back/templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>
{% include 'header.html' %}

<hr>

{% block content %}
    <h3 style="text-align:center"> 멋블리에 오신걸 환영 합니다.</h3>
{% endblock %}

<hr>

{% include 'footer.html' %}

</body>
</html>

back/templates/footer.html
<div class ="footer">

    <div class="footer_button" >
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>오시는길</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 style="font-family: 'Nanum Pen Script', cursive;">멋블리</h6>
    </div>
</div>

back/templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>멋블리</title>

    <!-- Jquery -->
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- 테일윈드 -->
    <!--<link rel="stylesheet" href="{% static 'tailwind.output.css' %}">-->


    <!-- BOOTSTRAP LINK -->
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css">

    <!-- GOOLE FONT LINK -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

</head>

back/templates/header.html
<div class="header">
    <div>
        <h1 style="font-family: 'Nanum Pen Script', cursive;">멋블리</h1>
    </div>
    <div>
        <a style="margin-right:0.5rem;" href="{% url 'product:list' %}">
            <span>쇼핑하기</span>
        </a>


        <a style="margin-right:0.5rem;" href="{% url 'product:cart_items' %}">
            <span>장바구니</span>
        </a>
    </div>

    <div style="margin-top: 1rem;">
        {% if not user.is_authenticated %}
        <a style="margin-right:1rem;" href="{% url 'account:signup' %}">
            <span>SignUp</span>
        </a>
        <a style="margin-right:1rem;" href="{% url 'account:login' %}?next={{ request.path }}">
            <span>login</span>
        </a>
        {% else %}

        <a style="margin-right:1rem;" href="{% url 'account:logout' %}?next={{ request.path }}">
            <span>logout</span>
        </a>
        {% endif %}
    </div>
</div>